spring.application.name=documentManager

#Database configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/documentManager
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword
spring.jpa.show-sql=true
